FROM golang:1.26-alpine

WORKDIR /app

RUN apk add --no-cache git && \
    go install github.com/air-verse/air@latest

COPY go.mod go.sum ./

RUN go mod download

#will be overwritten by volume mount in docker-compose.yml
COPY . . 

#Even if the backend is compromised, it runs as a non‑root user
RUN adduser --disabled-password --gecos '' codesmart
USER codesmart

EXPOSE 8080

# CMD ["go", "run", "./cmd/api/main.go"]

CMD ["air", "-c", ".air.toml"]